---
title: "Chapter 2: Biogeography of microeukaryotes in anoxic and hypersaline polar freshwater"
format: html
editor: visual
code-fold: true
---

### Notes/unused script

```{r}
#Identify ASVs with confidence ≤ 0.97
#low_confidence_indices<-which(as.numeric(PRJNA329332_V4_taxonomy_df$Confidence)<=0.97)
#Replace taxonomic assignments with "Unidentified" for those ASVs
#taxonomy_columns<-setdiff(colnames(PRJNA329332_V4_taxonomy_df),"Confidence")
#PRJNA329332_V4_taxonomy_df[low_confidence_indices,taxonomy_columns]<-"Unidentified"
#Convert to matrix for phyloseq compatibility
#PRJNA329332_V4_taxonomy_97<-as.matrix(PRJNA329332_V4_taxonomy_df)
#Count number of unidentified sequences...
```

## Set working directory

```{r}
#Set working directory
setwd("C:/Users/ac1552/OneDrive - Natural History Museum/Documents/PhD/Biogeography/R/Biogeography")
```

## Installing and loading packages

```{r}
#Load libraries
#install.packages("ggplot2")
require(ggplot2)
#install.packages("ggforce")
require(ggforce)
#install.packages("ggtree")
require(ggtree)
#if (!require("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")
#if(!requireNamespace("BiocManager")){
#  install.packages("BiocManager")
#BiocManager::install("phyloseq",force=T)
#BiocManager::install("XVector")
#BiocManager::install("UCSC.utils")
require(phyloseq)
require(tidyr)
#install.packages("forcats")
require(forcats)
require(plyr)
require(dplyr)
#for rownames_to_column() function
require(tibble)
#for write_tsv() function
require(readr)
#BiocManager::install("microbiome")
require(microbiome)
#install.packages("vegan")
require(vegan)
#install.packages("labdsv")
require(labdsv)
#install.packages("devtools")
#devtools::install_github("jiho/chroma")
require(chroma)
#install.packages("RColorBrewer")
require(RColorBrewer)
#install.packages("flextable")
require(flextable)
#install.packages("lme4")
#install.packages("lmtest")
require(lme4)
require(lmtest)
require(stringr)
require(grid)
require(scales)
require(gridExtra)
#install.packages("FSA")
require(FSA)
#install.packages("phytools")
require(phytools)
#install.packages("devtools")
#devtools::install_github("jfq3/QsRutils", build_vignettes = TRUE)
require(QsRutils)
#install.packages("ggrepel")
require(ggrepel)
#install.packages("Polychrome")
require(Polychrome)
#install.packages("remotes")
#BiocManager::install("ggtreeExtra")
require(ggtreeExtra)
#install.packages("ggnewscale")
require(ggnewscale)
```

## Set functions

```{r}
#Functions
#Prune 0 abundance records and samples from a PhyloSeq object
prune_ps<-function(ps){
  ps<-prune_samples(sample_sums(ps)>0,ps)
  ps<-prune_taxa(taxa_sums(ps)>0,ps)
  return(ps)
}

#Prune 0 abundance records from dataframe 
prune_0<-function(df){
  df<-df%>%filter(df$Abundance>0)
}

#18S Processing function
#PhyloSeq object input and glom mode
process_ps_18S<-function(ps,glom="tip",transformation="none",remove_na=T){
  #Remove 0 count taxa from PhyloSeq object
  ps<-prune_ps(ps)
  #If division agglomeration requested, otherwise do tipglom
  if(remove_na==F){
      if(glom=="Domain"){
      ps<-tax_glom(ps,taxrank="Domain",NArm=F)
    } else if(glom=="Supergroup"){
      ps<-tax_glom(ps,taxrank="Supergroup",NArm=F)
    } else if(glom=="Division"){
      ps<-tax_glom(ps,taxrank="Division",NArm=F)
    } else if(glom=="Subdivision"){
      ps<-tax_glom(ps,taxrank="Subdivision",NArm=F)
    } else if(glom=="Class"){
      ps<-tax_glom(ps,taxrank="Class",NArm=F)
    } else if(glom=="Order"){
      ps<-tax_glom(ps,taxrank="Order",NArm=F)
    } else if(glom=="Family"){
      ps<-tax_glom(ps,taxrank="Family",NArm=F)
    } else if(glom=="Genus"){
      ps<-tax_glom(ps,taxrank="Genus",NArm=F)
    } else if(glom=="Species"){
      ps<-tax_glom(ps,taxrank="Species",NArm=F)
    } else if(glom=="tip"){
      ps<-tip_glom(ps,h=0.001)
    }
  }
  else if(remove_na==T){
      if(glom=="Domain"){
      ps<-tax_glom(ps,taxrank="Domain")
    } else if(glom=="Supergroup"){
      ps<-tax_glom(ps,taxrank="Supergroup")
    } else if(glom=="Division"){
      ps<-tax_glom(ps,taxrank="Division")
    } else if(glom=="Subdivision"){
      ps<-tax_glom(ps,taxrank="Subdivision")
    } else if(glom=="Class"){
      ps<-tax_glom(ps,taxrank="Class")
    } else if(glom=="Order"){
      ps<-tax_glom(ps,taxrank="Order")
    } else if(glom=="Family"){
      ps<-tax_glom(ps,taxrank="Family")
    } else if(glom=="Genus"){
      ps<-tax_glom(ps,taxrank="Genus")
    } else if(glom=="Species"){
      ps<-tax_glom(ps,taxrank="Species")
    } else if(glom=="tip"){
      ps<-tip_glom(ps,h=0.01)
    }
  }
    #0.2 is the default value, 0.01 is the value which still retained quite a lot of info
  #If transformation is comp, then if pa, otherwise nothing
  if(transformation=="comp"){
    ps<-microbiome::transform(ps,"compositional")
  } else if(transformation=="pa"){
    ps<-microbiome::transform(ps,"pa")
  } else if(transformation=="none"){
    ps
  }
  return(ps)
}

#Theme function
theme_mine <- function(base_size=12,base_family="") {
  # Starts with theme_grey and then modify some parts
  theme_bw(base_size=base_size,base_family=base_family,
           base_line_size=base_size/24,base_rect_size=base_size/24)%+replace%
    theme(
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      strip.text.y = element_text(size = 18),
      axis.text.x = element_text(size=14),
      axis.text.y = element_text(size=14,hjust=1),
      axis.ticks =  element_line(colour = "black"), 
      axis.title.x= element_text(size=16),
      axis.title.y= element_text(size=16,angle=90),
      #legend.position = "none", 
      panel.background = element_blank(), 
      panel.border =element_blank(), 
      #panel.grid.major = element_blank(), 
      #panel.grid.minor = element_blank(), 
      panel.margin = unit(1.0, "lines"), 
      plot.background = element_blank(), 
      plot.margin = unit(c(0.5,  0.5, 0.5, 0.5), "lines"),
      axis.line = element_line(colour = "black")
    )
}

#Bubble theme
theme_bubble <- function(base_size=12,base_family="") {
  # Starts with theme_grey and then modify some parts
  theme_bw(base_size=base_size,base_family=base_family,
           base_line_size=base_size/24,base_rect_size=base_size/24)%+replace%
    theme(
      strip.background = element_blank(),
      strip.text.x = element_text(size = 18),
      strip.text.y = element_text(size = 18),
      axis.text.x = element_text(size=14,angle=90),
      axis.text.y = element_text(size=14,hjust=1),
      axis.ticks =  element_line(colour = "black"), 
      axis.title.x= element_text(size=16),
      axis.title.y= element_text(size=16,angle=90),
      #legend.position = "none", 
      panel.background = element_blank(), 
      panel.border =element_blank(), 
      #panel.grid.major = element_blank(), 
      #panel.grid.minor = element_blank(), 
      panel.margin = unit(1.0, "lines"), 
      plot.background = element_blank(), 
      plot.margin = unit(c(0.5,  0.5, 0.5, 0.5), "lines"),
      axis.line = element_line(colour = "black")
    )
}

remove_phyloseq_tree <- function(ps) {
  phyloseq::phyloseq(
    otu_table(ps),
    tax_table(ps),
    sample_data(ps)
  )
}
```

## Importing PRJNAs as separate phyloseq objects

### PRJNA329332

```{r}
#Read in OTU table
PRJNA329332_V4_otu_table=read.csv("data/PRJNA329332/V4_18S_PRJNA329332_table.csv",sep=",",row.names=1,na.strings="")
PRJNA329332_V4_otu_table=as.matrix(PRJNA329332_V4_otu_table)

#Read in taxonomy
PRJNA329332_V4_taxonomy=read.csv("data/PRJNA329332/V4_18S-PRJNA329332-pr2-taxonomy.csv",sep=",",row.names=1,na.strings="")
PRJNA329332_V4_taxonomy_df<-as.data.frame(PRJNA329332_V4_taxonomy)
#Filter out low confidence assignments
PRJNA329332_V4_taxonomy_97_df<-PRJNA329332_V4_taxonomy_df%>%filter(as.numeric(Confidence)>=0.97)
PRJNA329332_V4_taxonomy_97=as.matrix(PRJNA329332_V4_taxonomy_97_df)

#Read in metadata
#V9_18S
PRJNA329332_V4_metadata=read.csv("data/PRJNA329332/V4_18S_PRJNA329332_metadata.csv",row.names=1,na.strings="")

#Import as PhyloSeq objects
OTU_PRJNA329332_V4=otu_table(PRJNA329332_V4_otu_table,taxa_are_rows=TRUE)
TAX_PRJNA329332_V4=tax_table(PRJNA329332_V4_taxonomy_97)
META_PRJNA329332_V4=sample_data(PRJNA329332_V4_metadata)

#Check sample names are identical and same order
sample_names(OTU_PRJNA329332_V4)
sample_names(META_PRJNA329332_V4)

#Merge into one PhyloSeq object
ps_PRJNA329332_V4=phyloseq(OTU_PRJNA329332_V4,TAX_PRJNA329332_V4,META_PRJNA329332_V4)
ps_PRJNA329332_V4

#Filter out any ASVs not assigned further than 'Eukaryota' by removing any with 'NA' in the next taxonomic rank (Supergroup)
keep_taxa<-taxa_names(ps_PRJNA329332_V4)[!is.na(tax_table(ps_PRJNA329332_V4)[,"Supergroup"])]
ps_PRJNA329332_V4<-prune_taxa(keep_taxa,ps_PRJNA329332_V4)

#Add prefix to front of ASVs in ASV table and taxonomy table
prefix<-"PRJNA329332_"
old_names<-taxa_names(ps_PRJNA329332_V4)
new_names<-paste0(prefix,old_names)
taxa_names(ps_PRJNA329332_V4)<-new_names
otu_table(ps_PRJNA329332_V4)<-otu_table(ps_PRJNA329332_V4)[new_names,]
tax_table(ps_PRJNA329332_V4)<-tax_table(ps_PRJNA329332_V4)[new_names,]
```

### PRJNA803180

```{r}
#Read in OTU table
PRJNA803180_V4_otu_table=read.csv("data/PRJNA803180/V4_18S_PRJNA803180_table.csv",sep=",",row.names=1,na.strings="")
PRJNA803180_V4_otu_table=as.matrix(PRJNA803180_V4_otu_table)

#Read in taxonomy
PRJNA803180_V4_taxonomy=read.csv("data/PRJNA803180/V4_18S-PRJNA803180-pr2-taxonomy.csv",sep=",",row.names=1,na.strings="")
PRJNA803180_V4_taxonomy_df<-as.data.frame(PRJNA803180_V4_taxonomy)
#Filter out low confidence assignments
PRJNA803180_V4_taxonomy_97_df<-PRJNA803180_V4_taxonomy_df%>%filter(as.numeric(Confidence)>=0.97)
PRJNA803180_V4_taxonomy_97=as.matrix(PRJNA803180_V4_taxonomy_97_df)

#Read in metadata
#V9_18S
PRJNA803180_V4_metadata=read.csv("data/PRJNA803180/V4_18S_PRJNA803180_metadata.csv",row.names=1,na.strings="")

#Import as PhyloSeq objects
OTU_PRJNA803180_V4=otu_table(PRJNA803180_V4_otu_table,taxa_are_rows=TRUE)
TAX_PRJNA803180_V4=tax_table(PRJNA803180_V4_taxonomy_97)
META_PRJNA803180_V4=sample_data(PRJNA803180_V4_metadata)

#Check sample names are identical and same order
sample_names(OTU_PRJNA803180_V4)
sample_names(META_PRJNA803180_V4)

#Merge into one PhyloSeq object
ps_PRJNA803180_V4=phyloseq(OTU_PRJNA803180_V4,TAX_PRJNA803180_V4,META_PRJNA803180_V4)
ps_PRJNA803180_V4

#Filter out any ASVs not assigned further than 'Eukaryota' by removing any with 'NA' in the next taxonomic rank (Supergroup)
keep_taxa<-taxa_names(ps_PRJNA803180_V4)[!is.na(tax_table(ps_PRJNA803180_V4)[,"Supergroup"])]
ps_PRJNA803180_V4<-prune_taxa(keep_taxa,ps_PRJNA803180_V4)

#Add prefix to front of ASVs in ASV table and taxonomy table
prefix<-"PRJNA803180_"
old_names<-taxa_names(ps_PRJNA803180_V4)
new_names<-paste0(prefix,old_names)
taxa_names(ps_PRJNA803180_V4)<-new_names
otu_table(ps_PRJNA803180_V4)<-otu_table(ps_PRJNA803180_V4)[new_names,]
tax_table(ps_PRJNA803180_V4)<-tax_table(ps_PRJNA803180_V4)[new_names,]
```

### PRJNA805287

```{r}
#Read in OTU table
PRJNA805287_V4_otu_table=read.csv("data/PRJNA805287/V4_18S_PRJNA805287_table.csv",sep=",",row.names=1,na.strings="")
PRJNA805287_V4_otu_table=as.matrix(PRJNA805287_V4_otu_table)

#Read in taxonomy
PRJNA805287_V4_taxonomy=read.csv("data/PRJNA805287/V4_18S-PRJNA805287-pr2-taxonomy.csv",sep=",",row.names=1,na.strings="")
PRJNA805287_V4_taxonomy_df<-as.data.frame(PRJNA805287_V4_taxonomy)
#Filter out low confidence assignments
PRJNA805287_V4_taxonomy_97_df<-PRJNA805287_V4_taxonomy_df%>%filter(as.numeric(Confidence)>=0.97)
PRJNA805287_V4_taxonomy_97=as.matrix(PRJNA805287_V4_taxonomy_97_df)

#Read in metadata
#V9_18S
PRJNA805287_V4_metadata=read.csv("data/PRJNA805287/V4_18S_PRJNA805287_metadata.csv",row.names=1,na.strings="")

#Import as PhyloSeq objects
OTU_PRJNA805287_V4=otu_table(PRJNA805287_V4_otu_table,taxa_are_rows=TRUE)
TAX_PRJNA805287_V4=tax_table(PRJNA805287_V4_taxonomy_97)
META_PRJNA805287_V4=sample_data(PRJNA805287_V4_metadata)

#Check sample names are identical and same order
sample_names(OTU_PRJNA805287_V4)
sample_names(META_PRJNA805287_V4)

#Merge into one PhyloSeq object
ps_PRJNA805287_V4=phyloseq(OTU_PRJNA805287_V4,TAX_PRJNA805287_V4,META_PRJNA805287_V4)
ps_PRJNA805287_V4

#Filter out any ASVs not assigned further than 'Eukaryota' by removing any with 'NA' in the next taxonomic rank (Supergroup)
keep_taxa<-taxa_names(ps_PRJNA805287_V4)[!is.na(tax_table(ps_PRJNA805287_V4)[,"Supergroup"])]
ps_PRJNA805287_V4<-prune_taxa(keep_taxa,ps_PRJNA805287_V4)

#Add prefix to front of ASVs in ASV table and taxonomy table
prefix<-"PRJNA805287_"
old_names<-taxa_names(ps_PRJNA805287_V4)
new_names<-paste0(prefix,old_names)
taxa_names(ps_PRJNA805287_V4)<-new_names
otu_table(ps_PRJNA805287_V4)<-otu_table(ps_PRJNA805287_V4)[new_names,]
tax_table(ps_PRJNA805287_V4)<-tax_table(ps_PRJNA805287_V4)[new_names,]
```

### PRJNA838732

```{r}
#Read in OTU table
PRJNA838732_V4_otu_table=read.csv("data/PRJNA838732/V4_18S_PRJNA838732_table.csv",sep=",",row.names=1,na.strings="")
PRJNA838732_V4_otu_table=as.matrix(PRJNA838732_V4_otu_table)

#Read in taxonomy
PRJNA838732_V4_taxonomy=read.csv("data/PRJNA838732/V4_18S-PRJNA838732-pr2-taxonomy.csv",sep=",",row.names=1,na.strings="")
PRJNA838732_V4_taxonomy_df<-as.data.frame(PRJNA838732_V4_taxonomy)
#Filter out low confidence assignments
PRJNA838732_V4_taxonomy_97_df<-PRJNA838732_V4_taxonomy_df%>%filter(as.numeric(Confidence)>=0.97)
PRJNA838732_V4_taxonomy_97=as.matrix(PRJNA838732_V4_taxonomy_97_df)

#Read in metadata
#V9_18S
PRJNA838732_V4_metadata=read.csv("data/PRJNA838732/V4_18S_PRJNA838732_metadata.csv",row.names=1,na.strings="")

#Import as PhyloSeq objects
OTU_PRJNA838732_V4=otu_table(PRJNA838732_V4_otu_table,taxa_are_rows=TRUE)
TAX_PRJNA838732_V4=tax_table(PRJNA838732_V4_taxonomy_97)
META_PRJNA838732_V4=sample_data(PRJNA838732_V4_metadata)

#Check sample names are identical and same order
sample_names(OTU_PRJNA838732_V4)
sample_names(META_PRJNA838732_V4)

#Merge into one PhyloSeq object
ps_PRJNA838732_V4=phyloseq(OTU_PRJNA838732_V4,TAX_PRJNA838732_V4,META_PRJNA838732_V4)
ps_PRJNA838732_V4

#Filter out any ASVs not assigned further than 'Eukaryota' by removing any with 'NA' in the next taxonomic rank (Supergroup)
keep_taxa<-taxa_names(ps_PRJNA838732_V4)[!is.na(tax_table(ps_PRJNA838732_V4)[,"Supergroup"])]
ps_PRJNA838732_V4<-prune_taxa(keep_taxa,ps_PRJNA838732_V4)

#Add prefix to front of ASVs in ASV table and taxonomy table
prefix<-"PRJNA838732_"
old_names<-taxa_names(ps_PRJNA838732_V4)
new_names<-paste0(prefix,old_names)
taxa_names(ps_PRJNA838732_V4)<-new_names
otu_table(ps_PRJNA838732_V4)<-otu_table(ps_PRJNA838732_V4)[new_names,]
tax_table(ps_PRJNA838732_V4)<-tax_table(ps_PRJNA838732_V4)[new_names,]
```

## Merging individual phyloseq objects together

```{r}
#Merge phyloseq objects
ps_merged_V4<-merge_phyloseq(ps_PRJNA329332_V4,ps_PRJNA803180_V4,ps_PRJNA805287_V4,ps_PRJNA838732_V4)

#How many ASVs and samples
ntaxa(ps_merged_V4)
nsamples(ps_merged_V4)
```
